services:
  backend:
    build:
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data
    # No ports exposed! It's only on the docker network.

  frontend:
    build:
      dockerfile: web.Dockerfile
    ports:
      # Map container port 80 (Nginx) to host 9300
      # Use 127.0.0.1 to make it only accessible from your host Nginx
      - "127.0.0.1:9300:80"
    depends_on:
      - backend

  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data: