services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 9300:3000  # Frontend port
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  redis_data: